version: '3.7'
services:
  signaling:
    build:
      context: ./signaling
    hostname: signaling
    container_name: signaling
    volumes: 
      - ./data:/opt/data
      - ./signaling:/opt/signaling
    ports:
      - "9449:9449"
  webrtc:
    build: 
      context: ./webrtc-sample
    hostname: webrtc
    container_name: webrtc
    privileged: true
    devices:
      - /dev
    ports:
      - "3478:3478"
      - "3478:3478/udp"
      - "3033:3033"
      # 性能の低い端末だと、この個数のポートフォワーディングできない
      # - "59000-65000:59000-65000/udp"
    tty: true
    depends_on:
      - "signaling"
    command: >
      /opt/gst-webrtc-sample/build/gst-webrtc-sample
